# Generated by Django 4.0 on 2024-02-13 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='event_images/')),
                ('ticket_type', models.CharField(choices=[('Normal', 'Normal'), ('VIP', 'VIP')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('ticket_type', models.CharField(choices=[('Normal', 'Normal'), ('VIP', 'VIP')], max_length=10)),
                ('date_time', models.DateTimeField()),
                ('ticket_holder', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
