# Generated by Django 4.0 on 2024-02-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='resell_section',
            field=models.BooleanField(default=False),
        ),
    ]
