# Generated by Django 4.0 on 2024-02-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_resell_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='resell_section',
        ),
    ]
