# Generated by Django 4.0 on 2024-03-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_address_remove_account_phone_and_more'),
        ('event', '0006_alter_ticket_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_holder',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
