# Generated by Django 4.0 on 2024-03-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_remove_ticket_date_time_ticket_allow_resale'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reference_number',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
