# Generated by Django 4.0 on 2024-03-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_ticket_available_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='available_tickets',
        ),
        migrations.AddField(
            model_name='event',
            name='available_tickets',
            field=models.IntegerField(default=50),
        ),
    ]
