# Generated by Django 4.0 on 2024-04-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_remove_ticket_available_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='available_tickets',
        ),
    ]
