# Generated by Django 4.0 on 2024-04-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_remove_event_available_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_tickets',
            field=models.IntegerField(default=50),
        ),
    ]
